### ISSUE TITLE
requirements.txt 文件缺少模块

### ISSUE THREAD

**Issue by topdogs** [bboysoulcn/Fort#1]
在python3 中,yaml模块不是默认的,但没有在requirements.txt文件中.
使用python2,由于头没有“#coding:utf-8"导致中文失败.

**Comment by bboysoulcn** [comment]
> 在python3 中,yaml模块不是默认的,但没有在requirements.txt文件中.
> 
> 使用python2,由于头没有“#coding:utf-8"导致中文失败.

收到，大佬，这个不支持py2

**Comment by bboysoulcn** [comment]
> 在python3 中,yaml模块不是默认的,但没有在requirements.txt文件中.
> 使用python2,由于头没有“#coding:utf-8"导致中文失败.

提交了
